use an X11 window with mplayer wrapper too (-wid), because we create the window then we take all X11 events and only libplayer can control mplayer

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -35,12 +35,12 @@ show_help(){
   echo "  --enable-xine               build xine wrapper"
   echo "  --disable-xine              do not build xine wrapper"
   echo "  --with-xine-dir=DIR         check for libxine installed in DIR"
-  echo "  --with-X11-dir=DIR          check for libX11 installed in DIR"
   echo "  --enable-mplayer            build MPlayer wrapper"
   echo "  --disable-mplayer           do not build MPlayer wrapper"
   echo "  --enable-vlc                build VLC wrapper"
   echo "  --disable-vlc               do not build VLC wrapper"
   echo "  --with-vlc-dir=DIR          check for libvlc installed in DIR"
+  echo "  --with-X11-dir=DIR          check for libX11 installed in DIR"
   echo ""
   echo "Advanced options (experts only):"
   echo "  --disable-debug             disable debugging symbols"
@@ -400,8 +400,6 @@ for opt do
   ;;
   --with-xine-dir=*) libxinedir="$optval";
   ;;
-  --with-X11-dir=*) libX11dir="$optval";
-  ;;
   --enable-mplayer) wrapper_mplayer="yes";
   ;;
   --disable-mplayer) wrapper_mplayer="no";
@@ -411,6 +409,8 @@ for opt do
   --disable-vlc) wrapper_vlc="no";
   ;;
   --with-vlc-dir=*) libvlcdir="$optval";
+  ;;
+  --with-X11-dir=*) libX11dir="$optval";
   ;;
   --help) show_help
   ;;
@@ -600,15 +600,13 @@ fi
 #################################################
 #   check for libX11
 #################################################
-if test "$wrapper_xine" = "yes"; then
-  echolog "Checking for libX11 ..."
-  if [ -n "$libX11dir" ]; then
-    check_cflags -I$libX11dir
-    check_ldflags -L$libX11dir
-  fi
-  check_lib X11/X.h XInitThreads -lX11 || die "Error, can't find libX11 !"
-  add_extralibs -lX11
+echolog "Checking for libX11 ..."
+if [ -n "$libX11dir" ]; then
+  check_cflags -I$libX11dir
+  check_ldflags -L$libX11dir
 fi
+check_lib X11/X.h XInitThreads -lX11 || die "Error, can't find libX11 !"
+add_extralibs -lX11
 
 #################################################
 #   check for mplayer
