cosmetic: fix indent

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -762,19 +762,19 @@ fi
 #   check for libX11
 #################################################
 if test "$x11" = "auto" -o "$x11" = "yes"; then
-if test "$wrapper_xine" = "yes" -o "$wrapper_mplayer" = "yes"; then
-  x11="no"
-  echolog "Checking for libX11 ..."
-  if [ -n "$libX11dir" ]; then
-    check_cflags -I$libX11dir/include
-    check_ldflags -L$libX11dir/lib
+  if test "$wrapper_xine" = "yes" -o "$wrapper_mplayer" = "yes"; then
+    x11="no"
+    echolog "Checking for libX11 ..."
+    if [ -n "$libX11dir" ]; then
+      check_cflags -I$libX11dir/include
+      check_ldflags -L$libX11dir/lib
+    fi
+    check_lib X11/X.h XInitThreads -lX11 || die "Error, can't find libX11 !"
+    add_extralibs -lX11
+    add_extracflags -DUSE_X11
+    add_pkgconfig_requires x11
+    x11="yes"
   fi
-  check_lib X11/X.h XInitThreads -lX11 || die "Error, can't find libX11 !"
-  add_extralibs -lX11
-  add_extracflags -DUSE_X11
-  add_pkgconfig_requires x11
-  x11="yes"
-fi
 fi
 
 #################################################
