cosmetic: fix indentation

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -733,16 +733,16 @@ fi
 #   check for libX11
 #################################################
 if test "$wrapper_xine" = "yes" -o "$wrapper_mplayer" = "yes"; then
-x11="no"
-echolog "Checking for libX11 ..."
-if [ -n "$libX11dir" ]; then
-  check_cflags -I$libX11dir
-  check_ldflags -L$libX11dir
-fi
-check_lib X11/X.h XInitThreads -lX11 || die "Error, can't find libX11 !"
-add_extralibs -lX11 -lpthread
-add_pkgconfig_requires x11
-x11="yes"
+  x11="no"
+  echolog "Checking for libX11 ..."
+  if [ -n "$libX11dir" ]; then
+    check_cflags -I$libX11dir
+    check_ldflags -L$libX11dir
+  fi
+  check_lib X11/X.h XInitThreads -lX11 || die "Error, can't find libX11 !"
+  add_extralibs -lX11 -lpthread
+  add_pkgconfig_requires x11
+  x11="yes"
 fi
 
 #################################################
