sync with the configure script of libvalhalla

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -88,6 +88,11 @@ echolog(){
     echo "$@"
 }
 
+echologn(){
+    log "$@"
+    echo -n "$@"
+ }
+
 clean(){
     rm -f $TMPC $TMPO $TMPE $TMPS
 }
@@ -103,8 +108,24 @@ die(){
     exit 1
 }
 
+set_all(){
+    value=$1
+    shift
+    for var in $*; do
+        eval $var=$value
+    done
+}
+
+enable(){
+    set_all yes $*
+}
+
 enabled(){
     eval test "x\$$1" = "xyes"
+}
+
+disabled(){
+    eval test "x\$$1" = "xno"
 }
 
 flags_saved(){
@@ -347,6 +368,15 @@ check_libconfig_exists(){
     return $err
 }
 
+check_lib_version() {
+    local min_ver toobig_ver
+    min_ver="$2"
+    toobig_ver="$3"
+    check_cmd pkg-config --print-errors --exists "$1 >= $min_ver $1 < $toobig_ver" 2>>$logfile
+    err=$?
+    return $err
+}
+
 append_config(){
     echo "$@" >> $CONFIGFILE
 }
@@ -419,7 +449,8 @@ ar="ar"
 ranlib="ranlib"
 make="make"
 strip="strip"
-cpu=`uname -m`
+arch=`uname -m`
+cpu="generic"
 optimize="yes"
 small="no"
 debug="yes"
@@ -438,65 +469,6 @@ VERSION=""
 pkgconfig_requires=""
 logcolor="yes"
 doc="no"
-
-#################################################
-#   set cpu variable and specific cpu flags
-#################################################
-case "$cpu" in
-  i386|i486|i586|i686|i86pc|BePC)
-    cpu="x86"
-  ;;
-  x86_64|amd64)
-    cpu="x86"
-    canon_arch="`$cc -dumpmachine | sed -e 's,\([^-]*\)-.*,\1,'`"
-    if [ x"$canon_arch" = x"x86_64" -o x"$canon_arch" = x"amd64" ]; then
-      if [ -z "`echo $CFLAGS | grep -- -m32`"  ]; then
-        cpu="x86_64"
-      fi
-    fi
-  ;;
-# armv4l is a subset of armv5tel
-  arm|armv4l|armv5tel)
-    cpu="armv4l"
-  ;;
-  alpha)
-    cpu="alpha"
-  ;;
-  "Power Macintosh"|ppc|ppc64|powerpc)
-    cpu="powerpc"
-  ;;
-  mips|mipsel|IP*)
-    cpu="mips"
-  ;;
-  sun4u|sparc64)
-    cpu="sparc64"
-  ;;
-  sparc)
-    cpu="sparc"
-  ;;
-  sh4)
-    cpu="sh4"
-  ;;
-  parisc|parisc64)
-    cpu="parisc"
-  ;;
-  s390|s390x)
-    cpu="s390"
-  ;;
-  m68k)
-    cpu="m68k"
-  ;;
-  ia64)
-    cpu="ia64"
-  ;;
-  bfin)
-    cpu="bfin"
-  ;;
-  *)
-    cpu="unknown"
-  ;;
-esac
-
 
 #################################################
 #   check options
@@ -623,6 +595,110 @@ fi
 [ -n "$HOST_LDFLAGS" ] && HOST_LDFLAGS="$HOST_LDFLAGS"
 
 #################################################
+#   set arch variable and specific cpu flags
+#################################################
+if enabled cross_compile; then
+  arch="`$cc -dumpmachine | sed -e 's,\([^-]*\)-.*,\1,'`"
+fi
+
+case "$arch" in
+  i386|i486|i586|i686|i86pc|BePC)
+    arch="x86_32"
+  ;;
+  x86_64|amd64)
+    arch="x86_32"
+    canon_arch="`$cc -dumpmachine | sed -e 's,\([^-]*\)-.*,\1,'`"
+    if [ x"$canon_arch" = x"x86_64" -o x"$canon_arch" = x"amd64" ]; then
+      if [ -z "`echo $CFLAGS | grep -- -m32`"  ]; then
+        arch="x86_64"
+      fi
+    fi
+  ;;
+# armv4l is a subset of armv5tel
+  arm|armv4l|armv5tel)
+    arch="armv4l"
+  ;;
+  alpha)
+    arch="alpha"
+  ;;
+  "Power Macintosh"|ppc|ppc64|powerpc)
+    arch="powerpc"
+  ;;
+  mips|mipsel|IP*)
+    arch="mips"
+  ;;
+  sun4u|sparc64)
+    arch="sparc64"
+  ;;
+  sparc)
+    arch="sparc"
+  ;;
+  sh4)
+    arch="sh4"
+  ;;
+  parisc|parisc64)
+    arch="parisc"
+  ;;
+  s390|s390x)
+    arch="s390"
+  ;;
+  m68k)
+    arch="m68k"
+  ;;
+  ia64)
+    arch="ia64"
+  ;;
+  bfin)
+    arch="bfin"
+  ;;
+  *)
+    arch="unknown"
+  ;;
+esac
+
+# Add processor-specific flags
+if test $cpu != "generic"; then
+  case $cpu in
+    601|ppc601|PowerPC601)
+      add_cflags "-mcpu=601"
+    ;;
+    603*|ppc603*|PowerPC603*)
+      add_cflags "-mcpu=603"
+    ;;
+    604*|ppc604*|PowerPC604*)
+      add_cflags "-mcpu=604"
+    ;;
+    G3|g3|75*|ppc75*|PowerPC75*)
+      add_cflags "-mcpu=750 -mpowerpc-gfxopt"
+    ;;
+    G4|g4|745*|ppc745*|PowerPC745*)
+      add_cflags "-mcpu=7450 -mpowerpc-gfxopt"
+    ;;
+    74*|ppc74*|PowerPC74*)
+      add_cflags "-mcpu=7400 -mpowerpc-gfxopt"
+    ;;
+    G5|g5|970|ppc970|PowerPC970|power4*|Power4*)
+      add_cflags "-mcpu=970 -mpowerpc-gfxopt -mpowerpc64"
+    ;;
+    Cell|CELL|cell)
+      add_cflags "-mcpu=cell"
+    ;;
+    i[3456]86|pentium|pentium-mmx|pentiumpro|pentium[23]|pentium-m|k6|k6-[23]|winchip-c6|winchip2|c3|athlon|athlon-tbird|athlon-4|athlon-[mx]p|athlon64|k8|opteron|athlon-fx|core2|pentium4|pentium4m|prescott|nocona)
+      add_cflags "-march=$cpu"
+    ;;
+    sparc64)
+      add_cflags "-mcpu=v9"
+    ;;
+    arm*|cortex*)
+      add_cflags "-mcpu=$cpu"
+    ;;
+    *)
+      die "WARNING: Unknown CPU \"$cpu\", ignored."
+    ;;
+  esac
+fi
+
+#################################################
 #   create logging file
 #################################################
 if test "$logging" != no; then
@@ -632,7 +708,6 @@ if test "$logging" != no; then
 else
   logfile=/dev/null
 fi
-
 
 #################################################
 #   compiler sanity check
@@ -657,45 +732,14 @@ else
   dylib="no"
 fi
 
-
 #################################################
 #   check for target specific flags
 #################################################
 # check for SIMD availability
 
-# AltiVec flags: The FSF version of GCC differs from the Apple version
-if test $cpu = "powerpc"; then
-  if test $altivec = "yes"; then
-    if test -n "`$cc -v 2>&1 | grep version | grep Apple`"; then
-      add_cflags "-faltivec"
-    else
-      add_cflags "-maltivec -mabi=altivec"
-    fi
-  fi
-fi
-
-check_header altivec.h && _altivec_h=yes || _altivec_h=no
-
-# check if our compiler supports Motorola AltiVec C API
-if enabled altivec; then
-  if enabled _altivec_h; then
-    inc_altivec_h="#include <altivec.h>"
-  else
-    inc_altivec_h=
-  fi
-  check_cc <<EOF || altivec=no
-$inc_altivec_h
-int main(void) {
-    vector signed int v1, v2, v3;
-    v1 = vec_add(v2,v3);
-    return 0;
-}
-EOF
-fi
-
 # mmi only available on mips
 if [ "$mmi" = "default" ]; then
-  if [ "$cpu" = "mips" ]; then
+  if [ "$arch" = "mips" ]; then
     mmi="yes"
   else
     mmi="no"
@@ -724,7 +768,7 @@ return 0;
 EOF
 
 # test for mm3dnow.h
-test "$cpu" = "x86_64" && march=k8 || march=athlon
+test "$arch" = "x86_64" && march=k8 || march=athlon
 check_cc -march=$march <<EOF && mm3dnow=yes || mm3dnow=no
 #include <mm3dnow.h>
 int main(void) {
@@ -737,20 +781,10 @@ EOF
 
 # ---
 # big/little-endian test
-if test "$cross_compile" = "no"; then
-  check_ld <<EOF || die "endian test failed" && $TMPE && bigendian="yes"
-#include <inttypes.h>
-int main(int argc, char ** argv){
-        volatile uint32_t i=0x01234567;
-        return (*((uint8_t*)(&i))) == 0x67;
-}
+check_cc <<EOF || die "endian test failed"
+unsigned int endian = 'B' << 24 | 'I' << 16 | 'G' << 8 | 'E';
 EOF
-else
-# programs cannot be launched if cross compiling, so make a static guess
-  if test "$cpu" = "powerpc" -o "$cpu" = "mips" ; then
-    bigendian="yes"
-  fi
-fi
+od -A n -t x1 $TMPO | grep -q '42 *49 *47 *45' && enable bigendian
 
 # add some useful compiler flags if supported
 check_cflags -W
@@ -780,20 +814,13 @@ elif enabled optimize; then
 fi
 
 #################################################
-#   version
+#   check for shared library build
 #################################################
-temp_host_cflags "-Isrc"
-check_host_ld <<EOF
-#include <stdio.h>
-#include <player.h>
-int main(){
-  printf("LIBPLAYER_VERSION:"LIBPLAYER_VERSION_STR);
-  printf("\n");
-  return 0;
-}
-EOF
-VERSION=`strings $TMPE | sed -n -e 's,LIBPLAYER_VERSION:,,p'`
-restore_flags
+if test "$shared" = "yes" -o "$binding_python" = "yes"; then
+  case "$arch" in
+    x86_64|ia64|alpha|sparc*|power*) add_cflags "-fPIC" ;;
+  esac
+fi
 
 #################################################
 #   check for libxine
@@ -903,13 +930,20 @@ if test "$binding_python" = "auto" -o "$binding_python" = "yes"; then
 fi
 
 #################################################
-#   check for shared library build
+#   version
 #################################################
-if test "$shared" = "yes" -o "$binding_python" = "yes"; then
-  case "$cpu" in
-    x86_64|ia64|alpha|sparc*|power*) add_cflags "-fPIC" ;;
-  esac
-fi
+temp_host_cflags "-Isrc"
+check_host_ld <<EOF
+#include <stdio.h>
+#include <player.h>
+int main(){
+  printf("LIBPLAYER_VERSION:"LIBPLAYER_VERSION_STR);
+  printf("\n");
+  return 0;
+}
+EOF
+VERSION=`strings $TMPE | sed -n -e 's,LIBPLAYER_VERSION:,,p'`
+restore_flags
 
 #################################################
 #   Miscellaneous
@@ -938,7 +972,8 @@ echolog "  AR                 $ar"
 echolog "  RANLIB             $ranlib"
 echolog "  STRIP              $strip"
 echolog "  make               $make"
-echolog "  CPU                $cpu"
+echolog "  Architecture       $arch ($cpu)"
+echolog "  big-endian         ${bigendian-no}"
 echolog "  debug symbols      $debug"
 echolog "  strip symbols      $dostrip"
 echolog "  optimize           $optimize"
@@ -1002,6 +1037,10 @@ append_config "CPPFLAGS=$CPPFLAGS"
 append_config "OPTFLAGS=$CFLAGS"
 append_config "LDFLAGS=$LDFLAGS"
 append_config "INSTALL=$INSTALL"
+
+if enabled bigendian; then
+  append_config "WORDS_BIGENDIAN=yes"
+fi
 
 append_config "DEBUG=$debug"
 append_config "WRAPPER_XINE=$wrapper_xine"
